
version: '2'
services:
  backend:
    build:
      context: .  
      
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"  
    depends_on:
      - frontend 
    image: fzvis_backend:latest 
  frontend:
    build:
      context: .  
    ports:
      - "8080:8080"  
  
    image: fzvis_frontend:latest 