version: '2.24.5'
services:
  backend:
    build:
      context: .  # 后端应用程序的Dockerfile所在目录
      
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"  # 将后端应用程序的5000端口映射到宿主机器的5000端口
    depends_on:
      - frontend  # 指定依赖于前端服务
    image: fzvis_backend:latest 
  frontend:
    build:
      context: .  # 前端应用程序的Dockerfile所在目录
    ports:
      - "8080:8080"  # 将前端应用程序的80端口映射到宿主机器的80端口
  
    image: fzvis_frontend:latest 