#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$ROOT_DIR/.fzvis_config"

# Load memorized configuration if available
if [ -f "$CONFIG_FILE" ]; then
  # shellcheck source=/dev/null
  . "$CONFIG_FILE"
fi

SPACK_ROOT="${SPACK_ROOT:-"$HOME/.fzvis/spack"}"
SPACK_REPO_DIR="${SPACK_REPO_DIR:-"$HOME/.fzvis/spack_packages"}"
FZVIS_ENV_DIR="${FZVIS_ENV_DIR:-""}"
FZVIS_HOST="${FZVIS_HOST:-0.0.0.0}"
FZVIS_PORT="${FZVIS_PORT:-10080}"
SPACK_LIBPRESSIO_SPEC="${SPACK_LIBPRESSIO_SPEC:-libpressio+python+sz3+zfp+fpzip+mgard ^openblas~fortran}"
SPACK_NODE_SPEC="${SPACK_NODE_SPEC:-node-js@20:}"

FZVIS_SKIP_SPACK="${FZVIS_SKIP_SPACK:-0}"
FZVIS_SKIP_NODE="${FZVIS_SKIP_NODE:-0}"
FZVIS_SKIP_FRONTEND_BUILD="${FZVIS_SKIP_FRONTEND_BUILD:-0}"
FZVIS_NONINTERACTIVE="${FZVIS_NONINTERACTIVE:-0}"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

prompt_yes_no() {
  local prompt="$1"
  local default="${2:-Y}" # Y or N
  if [ "${FZVIS_NONINTERACTIVE:-0}" = "1" ]; then
    if [[ "$default" =~ ^[Yy]$ ]]; then return 0; else return 1; fi
  fi
  local prompt_suffix
  if [[ "$default" =~ ^[Yy]$ ]]; then
    prompt_suffix="[Y/n]"
  else
    prompt_suffix="[y/N]"
  fi
  while true; do
    local answer=""
    if ! read -rp "$prompt $prompt_suffix " answer; then
      answer="$default"
    fi
    answer="${answer:-$default}"
    case "$answer" in
      [Yy]* ) return 0 ;;
      [Nn]* ) return 1 ;;
      * ) echo "Please answer yes (y) or no (n)." ;;
    esac
  done
}

prompt_input() {
  local prompt="$1"
  local default="$2"
  if [ "${FZVIS_NONINTERACTIVE:-0}" = "1" ]; then
    echo "$default"
    return 0
  fi
  local answer=""
  if ! read -rp "$prompt [default: $default]: " answer; then
    answer="$default"
  fi
  answer="${answer:-$default}"
  echo "$answer"
}

resolve_path() {
  local p="$1"
  # Trim whitespace
  p="$(echo "$p" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
  # Expand leading tilde
  p="${p/#\~/$HOME}"
  # Resolve to absolute path
  if [ -d "$p" ]; then
    (cd "$p" && pwd)
  elif [ -d "$(dirname "$p")" ]; then
    echo "$(cd "$(dirname "$p")" && pwd)/$(basename "$p")"
  else
    echo "$p"
  fi
}

save_config() {
  cat > "$CONFIG_FILE" <<CONFEOF
# Auto-generated by install_fzvis.sh on $(date)
SPACK_ROOT="$SPACK_ROOT"
SPACK_REPO_DIR="$SPACK_REPO_DIR"
FZVIS_ENV_DIR="$FZVIS_ENV_DIR"
FZVIS_HOST="$FZVIS_HOST"
FZVIS_PORT="$FZVIS_PORT"
CONFEOF
  echo "[INFO] Configuration memorized in $CONFIG_FILE"
}

clone_or_update() {
  local repo_url="$1"
  local target_dir="$2"
  local branch="${3:-}"
  if [ -d "$target_dir/.git" ]; then
    echo "Updating repository in $target_dir..."
    git -C "$target_dir" fetch --depth 1 origin
    git -C "$target_dir" reset --hard FETCH_HEAD
    if [ -n "$branch" ]; then
      git -C "$target_dir" fetch --depth 1 origin "$branch"
      git -C "$target_dir" checkout "$branch" 2>/dev/null || git -C "$target_dir" checkout -B "$branch" FETCH_HEAD
      git -C "$target_dir" reset --hard FETCH_HEAD
    else
      git -C "$target_dir" fetch --depth 1 origin
      git -C "$target_dir" reset --hard FETCH_HEAD
    fi
  else
    echo "Cloning $repo_url to $target_dir..."
    git clone --depth 1 "$repo_url" "$target_dir"
    if [ -n "$branch" ]; then
      git clone --depth 1 --branch "$branch" "$repo_url" "$target_dir"
    else
      git clone --depth 1 "$repo_url" "$target_dir"
    fi
  fi
}

need_cmd git
need_cmd python3

# ============================================================
# 1. Spack Setup
# ============================================================
echo
echo "============================================================"
echo " 1. Spack Setup"
echo "============================================================"

DETECTED_SPACK_ROOT=""
if command -v spack >/dev/null 2>&1; then
  DETECTED_SPACK_ROOT="$(spack location -r 2>/dev/null || dirname "$(dirname "$(command -v spack)")")"
elif [ -f "$SPACK_ROOT/share/spack/setup-env.sh" ]; then
  DETECTED_SPACK_ROOT="$SPACK_ROOT"
fi

SKIP_SPACK_INSTALL=0
if [ -n "$DETECTED_SPACK_ROOT" ] && [ -f "$DETECTED_SPACK_ROOT/share/spack/setup-env.sh" ]; then
  SPACK_ROOT="$DETECTED_SPACK_ROOT"
  echo "[INFO] Existing Spack installation detected at: $SPACK_ROOT"
  if prompt_yes_no "Use existing Spack and skip downloading/updating Spack?" "Y"; then
    SKIP_SPACK_INSTALL=1
  fi
fi

if [ "$SKIP_SPACK_INSTALL" != "1" ] && [ "$FZVIS_SKIP_SPACK" != "1" ]; then
  echo "Installing or updating Spack in $SPACK_ROOT..."
  clone_or_update "https://github.com/spack/spack.git" "$SPACK_ROOT"
fi

if [ -f "$SPACK_ROOT/share/spack/setup-env.sh" ]; then
  # shellcheck source=/dev/null
  . "$SPACK_ROOT/share/spack/setup-env.sh"
else
  echo "Error: Spack environment setup script not found at $SPACK_ROOT/share/spack/setup-env.sh" >&2
  exit 1
fi

echo
echo "Checking Libpressio Spack package repository..."
if spack repo list 2>/dev/null | grep -q "spack_packages" || [ -d "$SPACK_REPO_DIR/.git" ]; then
  echo "[INFO] Libpressio repository already detected at: $SPACK_REPO_DIR"
  if prompt_yes_no "Skip updating Libpressio Spack package repository?" "Y"; then
    SKIP_REPO_UPDATE=1
  else
    SKIP_REPO_UPDATE=0
  fi
else
  SKIP_REPO_UPDATE=0
fi

if [ "${SKIP_REPO_UPDATE:-0}" != "1" ]; then
  echo "Adding or updating libpressio Spack package repository in $SPACK_REPO_DIR..."
  clone_or_update "https://github.com/robertu94/spack_packages.git" "$SPACK_REPO_DIR"
  spack repo add "$SPACK_REPO_DIR" || true
fi

# ============================================================
# 2. Spack Environment Setup (fzvis-env)
# ============================================================
echo
echo "============================================================"
echo " 2. Spack Environment Configuration (fzvis-env)"
echo "============================================================"

PARENT_DIR="$(cd "$ROOT_DIR/.." && pwd)"
DEFAULT_EXISTING_ENV=""
if [ -n "$FZVIS_ENV_DIR" ] && [ -d "$FZVIS_ENV_DIR" ]; then
  DEFAULT_EXISTING_ENV="$FZVIS_ENV_DIR"
elif [ -d "$PARENT_DIR/.spack-env" ] || [ -f "$PARENT_DIR/spack.yaml" ]; then
  DEFAULT_EXISTING_ENV="$PARENT_DIR"
else
  DEFAULT_EXISTING_ENV="$ROOT_DIR/fzvis-env"
fi

CHOICE="2"
if [ "${FZVIS_NONINTERACTIVE:-0}" = "1" ]; then
  if [ -n "$FZVIS_ENV_DIR" ]; then
    CHOICE="2"
  else
    CHOICE="1"
  fi
else
  echo "Please choose an option for the Spack environment:"
  echo "  1) Create a new Spack environment"
  echo "  2) Use an existing Spack environment"
  if [ -n "$DEFAULT_EXISTING_ENV" ] && { [ -d "$DEFAULT_EXISTING_ENV/.spack-env" ] || [ -f "$DEFAULT_EXISTING_ENV/spack.yaml" ]; }; then
    DEFAULT_CHOICE="2"
    echo "[INFO] Detected existing environment candidate: $DEFAULT_EXISTING_ENV"
  else
    DEFAULT_CHOICE="1"
  fi
  while true; do
    input_choice=""
    if ! read -rp "Select option [1/2] [default: $DEFAULT_CHOICE]: " input_choice; then
      input_choice="$DEFAULT_CHOICE"
    fi
    input_choice="${input_choice:-$DEFAULT_CHOICE}"
    if [ "$input_choice" = "1" ] || [ "$input_choice" = "2" ]; then
      CHOICE="$input_choice"
      break
    else
      echo "Please enter 1 or 2."
    fi
  done
fi

if [ "$CHOICE" = "1" ]; then
  DEFAULT_NEW_DIR="$ROOT_DIR/fzvis-env"
  CHOSEN_DIR="$(prompt_input "Enter directory path for the new environment" "$DEFAULT_NEW_DIR")"
  FZVIS_ENV_DIR="$(resolve_path "$CHOSEN_DIR")"
  echo "Configuring new Spack environment at: $FZVIS_ENV_DIR"
  if [ ! -d "$FZVIS_ENV_DIR/.spack-env" ] && [ ! -f "$FZVIS_ENV_DIR/spack.yaml" ]; then
    mkdir -p "$FZVIS_ENV_DIR"
    spack env create -d "$FZVIS_ENV_DIR"
  else
    echo "[INFO] Environment already exists at $FZVIS_ENV_DIR."
  fi
else
  CHOSEN_DIR="$(prompt_input "Enter the location of the existing Spack environment" "$DEFAULT_EXISTING_ENV")"
  FZVIS_ENV_DIR="$(resolve_path "$CHOSEN_DIR")"

  if [ ! -d "$FZVIS_ENV_DIR/.spack-env" ] && [ ! -f "$FZVIS_ENV_DIR/spack.yaml" ]; then
    echo "[WARNING] '$FZVIS_ENV_DIR' does not contain '.spack-env' or 'spack.yaml'."
    if ! prompt_yes_no "Continue with this directory anyway?" "N"; then
      echo "Installation cancelled. Please check the environment path and retry."
      exit 1
    fi
  else
    echo "[INFO] Verified existing Spack environment at: $FZVIS_ENV_DIR"
  fi
fi

echo "Activating Spack environment at $FZVIS_ENV_DIR..."
spack env activate -d "$FZVIS_ENV_DIR"

# Ensure system pkg-config search paths (including multiarch directories) are in PKG_CONFIG_PATH
# This is required because Spack's pkgconf does not search /usr/lib/<triplet>/pkgconfig by default
ARCH_TRIPLET="$(gcc -dumpmachine 2>/dev/null || uname -m)-linux-gnu"
for pcdir in \
  "/usr/lib/$ARCH_TRIPLET/pkgconfig" \
  "/usr/lib64/pkgconfig" \
  "/usr/lib/pkgconfig" \
  "/usr/local/lib/pkgconfig" \
  "/usr/local/share/pkgconfig" \
  "/usr/share/pkgconfig"; do
  if [ -d "$pcdir" ]; then
    export PKG_CONFIG_PATH="${PKG_CONFIG_PATH:+$PKG_CONFIG_PATH:}$pcdir"
  fi
done

# Memorize the environment configuration early so it persists even if subsequent steps fail
save_config

# ============================================================
# 3. Spack Dependencies (libpressio, python, node-js)
# ============================================================
echo
echo "============================================================"
echo " 3. Spack Dependencies (libpressio, python, node-js)"
echo "============================================================"

LIBPRESSIO_FOUND=0
if spack find libpressio >/dev/null 2>&1; then
  LIBPRESSIO_FOUND=1
fi

SKIP_SPACK_PACKAGES=0
if [ "$LIBPRESSIO_FOUND" = "1" ]; then
  INSTALLED_SPEC="$(spack find libpressio 2>/dev/null | grep -E '^libpressio' | head -n 1 | tr -s ' ' || echo "libpressio")"
  echo "[INFO] libpressio is ALREADY INSTALLED in this environment: $INSTALLED_SPEC"
  if prompt_yes_no "Skip adding and installing Spack dependencies (libpressio, etc.)?" "Y"; then
    SKIP_SPACK_PACKAGES=1
  fi
else
  echo "[INFO] libpressio was NOT found in this environment."
  if ! prompt_yes_no "Add and install Spack dependencies ($SPACK_LIBPRESSIO_SPEC)?" "Y"; then
    SKIP_SPACK_PACKAGES=1
  fi
fi

if [ "$SKIP_SPACK_PACKAGES" != "1" ]; then
  echo "Adding dependencies to Spack environment..."
  spack add py-pip python@3.10: $SPACK_LIBPRESSIO_SPEC
  if [ "$FZVIS_SKIP_NODE" != "1" ] && ! command -v node >/dev/null 2>&1; then
    spack add "$SPACK_NODE_SPEC"
  fi
  echo "Installing Spack environment dependencies..."
  spack install
else
  echo "[INFO] Skipping Spack package installation."
fi

# ============================================================
# 4. Python Requirements (requirements.txt)
# ============================================================
echo
echo "============================================================"
echo " 4. Python Requirements (requirements.txt)"
echo "============================================================"

PYTHON_REQ_OK=0
if python -c "import flask, flask_cors, netCDF4, numpy, openai, matplotlib, pywt, jwt, dotenv, cachetools, scipy" >/dev/null 2>&1; then
  PYTHON_REQ_OK=1
fi

SKIP_PIP=0
if [ "$PYTHON_REQ_OK" = "1" ]; then
  echo "[INFO] All required Python packages from requirements.txt are ALREADY INSTALLED."
  if prompt_yes_no "Skip running 'pip install -r requirements.txt'?" "Y"; then
    SKIP_PIP=1
  fi
else
  echo "[INFO] Some Python requirements are not installed in the current environment."
  if ! prompt_yes_no "Install Python requirements via pip?" "Y"; then
    SKIP_PIP=1
  fi
fi

if [ "$SKIP_PIP" != "1" ]; then
  echo "Installing Python requirements into Spack environment..."
  python -m ensurepip --upgrade >/dev/null 2>&1 || true
  python -m pip install --upgrade pip || true
  python -m pip install -r "$ROOT_DIR/requirements.txt" || true
else
  echo "[INFO] Skipping Python pip installation."
fi

# ============================================================
# 5. Frontend Dependencies & Build
# ============================================================
echo
echo "============================================================"
echo " 5. Frontend Dependencies & Build"
echo "============================================================"

SKIP_FRONTEND=0
if [ "$FZVIS_SKIP_FRONTEND_BUILD" = "1" ]; then
  SKIP_FRONTEND=1
  echo "[INFO] Frontend build skipped via FZVIS_SKIP_FRONTEND_BUILD=1"
elif [ -f "$ROOT_DIR/dist/index.html" ]; then
  echo "[INFO] Production frontend build ALREADY EXISTS at $ROOT_DIR/dist."
  if prompt_yes_no "Skip frontend dependency installation and build?" "Y"; then
    SKIP_FRONTEND=1
  fi
fi

if [ "$SKIP_FRONTEND" != "1" ]; then
  need_cmd npm
  if [ -d "$ROOT_DIR/node_modules" ]; then
    echo "[INFO] node_modules directory already exists."
    if prompt_yes_no "Skip 'npm ci' and only run 'npm run build'?" "Y"; then
      echo "Building frontend..."
      (cd "$ROOT_DIR" && npm run build)
    else
      echo "Installing frontend dependencies..."
      (cd "$ROOT_DIR" && npm ci)
      echo "Building frontend..."
      (cd "$ROOT_DIR" && npm run build)
    fi
  else
    echo "Installing frontend dependencies..."
    (cd "$ROOT_DIR" && npm ci)
    echo "Building frontend..."
    (cd "$ROOT_DIR" && npm run build)
  fi
else
  echo "[INFO] Skipping frontend build."
fi

# ============================================================
# 6. Dependencies: MSz and FFCz
# ============================================================
echo
echo "============================================================"
echo " 6. Dependencies: MSz and FFCz"
echo "============================================================"

OPT_DEPS_DIR="$ROOT_DIR/external"
mkdir -p "$OPT_DEPS_DIR"

# Check MSz
MSZ_INSTALLED=0
if python -c "import msz" >/dev/null 2>&1; then
  MSZ_INSTALLED=1
else
  # Check if python can import it with LD_LIBRARY_PATH and local site-packages
  PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "3.11")"
  if PYTHONPATH="$FZVIS_ENV_DIR/local/lib/python$PY_VER/site-packages:${PYTHONPATH:-}" LD_LIBRARY_PATH="$FZVIS_ENV_DIR/local/lib:${LD_LIBRARY_PATH:-}" python -c "import msz" >/dev/null 2>&1; then
    MSZ_INSTALLED=1
  fi
fi

if [ "$MSZ_INSTALLED" = "1" ]; then
  echo "[INFO] MSz is ALREADY INSTALLED and importable in Python."
  if prompt_yes_no "Skip building MSz?" "Y"; then
    BUILD_MSZ=0
  else
    BUILD_MSZ=1
  fi
else
  echo "[INFO] MSz is not installed (or not importable in Python)."
  if prompt_yes_no "Install MSz?" "Y"; then
    BUILD_MSZ=1
  else
    BUILD_MSZ=0
  fi
fi

if [ "$BUILD_MSZ" = "1" ]; then
  echo "Cloning and building MSz (branch 'fz' with Python bindings)..."
  clone_or_update "https://github.com/YuxiaoLi1234/MSz.git" "$OPT_DEPS_DIR/MSz" "fz"

  PY_VER="$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo "3.11")"
  LOCAL_SITE="$FZVIS_ENV_DIR/local/lib/python$PY_VER/site-packages"
  mkdir -p "$LOCAL_SITE"
  (
    cd "$OPT_DEPS_DIR/MSz"
    mkdir -p build && cd build
    cmake \
      -DPython3_EXECUTABLE="$(which python)" \
      -DCMAKE_INSTALL_PREFIX="$FZVIS_ENV_DIR/local" \
      -DCMAKE_INSTALL_RPATH="$FZVIS_ENV_DIR/local/lib" \
      -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
      -DMSZ_ENABLE_CUDA=OFF \
      ..
    make -j"$(nproc)"
    make install
  )
  # Ensure the compiled python module is in local site-packages
  for so_file in "$OPT_DEPS_DIR/MSz/build"/msz*.so; do
    if [ -f "$so_file" ]; then
      cp -f "$so_file" "$LOCAL_SITE/"
    fi
  done

  # Verify import
  export LD_LIBRARY_PATH="$FZVIS_ENV_DIR/local/lib:${LD_LIBRARY_PATH:-}"
  export PYTHONPATH="$LOCAL_SITE:${PYTHONPATH:-}"
  if python -c "import msz" >/dev/null 2>&1; then
    echo "[INFO] Verified: 'import msz' succeeded in Python!"
  else
    echo "[WARNING] 'import msz' failed after build. Please check external/MSz/build logs."
  fi
else
  echo "[INFO] Skipping MSz build."
fi

# Check FFCz
FFCZ_INSTALLED=0
if [ -x "$FZVIS_ENV_DIR/local/bin/ffcz" ] || [ -x "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz_cpu" ] || command -v ffcz >/dev/null 2>&1; then
  FFCZ_INSTALLED=1
fi

if [ "$FFCZ_INSTALLED" = "1" ]; then
  FFCZ_PATH="$(command -v ffcz 2>/dev/null || true)"
  if [ -z "$FFCZ_PATH" ] && [ -x "$FZVIS_ENV_DIR/local/bin/ffcz" ]; then
    FFCZ_PATH="$FZVIS_ENV_DIR/local/bin/ffcz"
  elif [ -z "$FFCZ_PATH" ]; then
    FFCZ_PATH="$OPT_DEPS_DIR/FFCz/CPU/build/ffcz_cpu"
  fi
  echo "[INFO] FFCz is ALREADY INSTALLED ($FFCZ_PATH)."
  if prompt_yes_no "Skip building FFCz?" "Y"; then
    BUILD_FFCZ=0
  else
    BUILD_FFCZ=1
  fi
else
  echo "[INFO] FFCz is not installed."
  # Check if required FFTW3 dependencies (fftw3, fftw3f) are available in pkg-config
  FFTW_AVAILABLE=0
  if pkg-config --exists fftw3 fftw3f 2>/dev/null; then
    FFTW_AVAILABLE=1
  fi

  if [ "$FFTW_AVAILABLE" != "1" ]; then
    echo "[WARNING] FFCz requires FFTW3 (single and double precision: fftw3 and fftw3f)."
    echo "          Missing fftw3/fftw3f pkg-config definitions."
    echo "          To install on Ubuntu/Debian: sudo apt-get install -y libfftw3-dev"
    if ! prompt_yes_no "Attempt building FFCz anyway?" "N"; then
      BUILD_FFCZ=0
    else
      BUILD_FFCZ=1
    fi
  else
    if prompt_yes_no "Install FFCz?" "Y"; then
      BUILD_FFCZ=1
    else
      BUILD_FFCZ=0
    fi
  fi
fi

if [ "$BUILD_FFCZ" = "1" ]; then
  echo "Cloning and building FFCz..."
  clone_or_update "https://github.com/guoxiliu/FFCz.git" "$OPT_DEPS_DIR/FFCz"
  (
    cd "$OPT_DEPS_DIR/FFCz/CPU"
    mkdir -p build && cd build
    cmake .. -DCMAKE_BUILD_TYPE=Release
    make -j"$(nproc)"
  )
  mkdir -p "$FZVIS_ENV_DIR/local/bin"
  if [ -f "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz_cpu" ]; then
    ln -sf "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz_cpu" "$FZVIS_ENV_DIR/local/bin/ffcz"
    ln -sf "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz_cpu" "$FZVIS_ENV_DIR/local/bin/ffcz_cpu"
    echo "[INFO] FFCz binary linked to $FZVIS_ENV_DIR/local/bin/ffcz and ffcz_cpu"
  elif [ -f "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz" ]; then
    ln -sf "$OPT_DEPS_DIR/FFCz/CPU/build/ffcz" "$FZVIS_ENV_DIR/local/bin/ffcz"
  fi

  # Verify FFCz execution
  if [ -x "$FZVIS_ENV_DIR/local/bin/ffcz" ] && ("$FZVIS_ENV_DIR/local/bin/ffcz" 2>&1 || true) | grep -qi "usage"; then
    echo "[INFO] Verified: FFCz binary executed successfully!"
  else
    echo "[WARNING] FFCz binary execution test failed. Please check build logs."
  fi
else
  echo "[INFO] Skipping FFCz build."
fi

# ============================================================
# 7. Runner Script Generation
# ============================================================
echo
echo "============================================================"
echo " 7. Generating Runner Script"
echo "============================================================"

# Final save to ensure all variables are written
save_config

cat > "$ROOT_DIR/scripts/run_fzvis.sh" <<RUNEOF
#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"

# Load saved configuration if present
if [ -f "\$ROOT_DIR/.fzvis_config" ]; then
  . "\$ROOT_DIR/.fzvis_config"
fi

SPACK_ROOT="\${SPACK_ROOT:-"$SPACK_ROOT"}"
FZVIS_ENV_DIR="\${FZVIS_ENV_DIR:-"$FZVIS_ENV_DIR"}"

if [ -f "\$SPACK_ROOT/share/spack/setup-env.sh" ]; then
  # shellcheck source=/dev/null
  . "\$SPACK_ROOT/share/spack/setup-env.sh"
  if [ -d "\$FZVIS_ENV_DIR/.spack-env" ] || [ -f "\$FZVIS_ENV_DIR/spack.yaml" ]; then
    spack env activate -d "\$FZVIS_ENV_DIR"
  elif spack env list 2>/dev/null | grep -qw "\$FZVIS_ENV_DIR"; then
    spack env activate "\$FZVIS_ENV_DIR"
  fi
fi

export PATH="\$FZVIS_ENV_DIR/local/bin:\$PATH"
export LD_LIBRARY_PATH="\$FZVIS_ENV_DIR/local/lib:\${LD_LIBRARY_PATH:-}"

# Dynamic site-packages discovery
for sp in "\$FZVIS_ENV_DIR"/local/lib/python*/site-packages; do
  if [ -d "\$sp" ]; then
    export PYTHONPATH="\$sp:\${PYTHONPATH:-}"
  fi
done

cd "\$ROOT_DIR"
python src/server/main.py --HOST "\${FZVIS_HOST:-$FZVIS_HOST}" --PORT "\${FZVIS_PORT:-$FZVIS_PORT}" "\$@"
RUNEOF

chmod +x "$ROOT_DIR/scripts/run_fzvis.sh"

echo
echo "============================================================"
echo "FZ-VIS installation complete!"
echo "============================================================"
echo "Active environment: $FZVIS_ENV_DIR"
echo
echo "Component Verification Status:"
if python -c "import msz; assert hasattr(msz, 'extract_critical_points')" >/dev/null 2>&1; then
  echo "  - MSz (Python module):       INSTALLED & VERIFIED"
else
  echo "  - MSz (Python module):       NOT AVAILABLE"
fi

if [ -x "$FZVIS_ENV_DIR/local/bin/ffcz" ] && ("$FZVIS_ENV_DIR/local/bin/ffcz" 2>&1 || true) | grep -qi "usage"; then
  echo "  - FFCz (binary executable):  INSTALLED & VERIFIED"
else
  echo "  - FFCz (binary executable):  NOT AVAILABLE"
fi

if [ -f "$ROOT_DIR/dist/index.html" ]; then
  echo "  - Frontend (dist/):          BUILT & READY"
else
  echo "  - Frontend (dist/):          NOT BUILT"
fi

echo
echo "Start the application with:"
echo "  $ROOT_DIR/scripts/run_fzvis.sh"
echo
echo "Then access in browser at:"
echo "  http://localhost:$FZVIS_PORT"
